In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sn
import pprint


from scipy import stats

In [3]:
file = "Resources/arcos-or-statewide-itemized.csv"
df = pd.read_csv(file)
df.head()

/Users/aaron/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (3,5,22,26) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,REPORTER_DEA_NO,REPORTER_BUS_ACT,REPORTER_NAME,REPORTER_ADDL_CO_INFO,REPORTER_ADDRESS1,REPORTER_ADDRESS2,REPORTER_CITY,REPORTER_STATE,REPORTER_ZIP,REPORTER_COUNTY,...,DOSAGE_UNIT,TRANSACTION_ID,Product_Name,Ingredient_Name,Measure,MME_Conversion_Factor,Combined_Labeler_Name,Reporter_family,dos_str,MME
0,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,300.0,5029,OXYCODONE HCL 40MG TABS,OXYCODONE HYDROCHLORIDE,TAB,1.5,"Actavis Pharma, Inc.",Bellco Drug Corp,40.0,16137.00
1,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,1000.0,1592,HYDROCODONE.BIT. & ACETA 5MG & 500M,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,Par Pharmaceutical,Bellco Drug Corp,5.0,3027.00
2,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,600.0,331,HYDROCODONE BITARTRATE/ACETA 7.5MG/3,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,Par Pharmaceutical,Bellco Drug Corp,7.5,2724.30
3,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,1000.0,8633,"HYDROCODONE.BIT./ACET.,10MG & 325MG/",HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,Par Pharmaceutical,Bellco Drug Corp,10.0,6054.00
4,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,500.0,7829,HYDROCODONE/APAP 7.5MG/200MG TABS.,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,Par Pharmaceutical,Bellco Drug Corp,7.5,2270.25

In [19]:
wa_file = "Resources/arcos-wa-statewide-itemized.csv"
wa_df = pd.read_csv(wa_file)
wa_df.head()

/Users/aaron/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (3,5,22,26,27) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,REPORTER_DEA_NO,REPORTER_BUS_ACT,REPORTER_NAME,REPORTER_ADDL_CO_INFO,REPORTER_ADDRESS1,REPORTER_ADDRESS2,REPORTER_CITY,REPORTER_STATE,REPORTER_ZIP,REPORTER_COUNTY,...,DOSAGE_UNIT,TRANSACTION_ID,Product_Name,Ingredient_Name,Measure,MME_Conversion_Factor,Combined_Labeler_Name,Reporter_family,dos_str,MME
0,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,800.0,4210,HYDROCODONE BIT. & IBUPROPHEN 7.5MG/,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,"Actavis Pharma, Inc.",Bellco Drug Corp,7.5,3632.4
1,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,100.0,4123,HYDROCODONE BIT/ACETA 5MG/325MG USP,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,SpecGx LLC,Bellco Drug Corp,5.0,302.7
2,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,300.0,4031,OXYCODONE HYDROCHLORIDE CR 20MG TABL,OXYCODONE HYDROCHLORIDE,TAB,1.5,"Actavis Pharma, Inc.",Bellco Drug Corp,20.0,8068.5
3,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,500.0,7551,HYDROCODONE BIT. 10MG/ACETAMINOPHEN,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,"Actavis Pharma, Inc.",Bellco Drug Corp,10.0,3027.0
4,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,500.0,4807,HYDROCODONE BIT. 10MG/ACETAMINOPHEN,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,"Actavis Pharma, Inc.",Bellco Drug Corp,10.0,3027.0

In [ ]:
#the column gave a warning for columns [3, 45, 22, 26].

In [4]:
#Print column headers for cleaner look:

df.columns

Index(['REPORTER_DEA_NO', 'REPORTER_BUS_ACT', 'REPORTER_NAME',
       'REPORTER_ADDL_CO_INFO', 'REPORTER_ADDRESS1', 'REPORTER_ADDRESS2',
       'REPORTER_CITY', 'REPORTER_STATE', 'REPORTER_ZIP', 'REPORTER_COUNTY',
       'BUYER_DEA_NO', 'BUYER_BUS_ACT', 'BUYER_NAME', 'BUYER_ADDL_CO_INFO',
       'BUYER_ADDRESS1', 'BUYER_ADDRESS2', 'BUYER_CITY', 'BUYER_STATE',
       'BUYER_ZIP', 'BUYER_COUNTY', 'TRANSACTION_CODE', 'DRUG_CODE', 'NDC_NO',
       'DRUG_NAME', 'QUANTITY', 'UNIT', 'ACTION_INDICATOR', 'ORDER_FORM_NO',
       'CORRECTION_NO', 'STRENGTH', 'TRANSACTION_DATE', 'CALC_BASE_WT_IN_GM',
       'DOSAGE_UNIT', 'TRANSACTION_ID', 'Product_Name', 'Ingredient_Name',
       'Measure', 'MME_Conversion_Factor', 'Combined_Labeler_Name',
       'Reporter_family', 'dos_str', 'MME'],
      dtype='object')

In [5]:
# View values in Column [3]
reporters = df["REPORTER_ADDL_CO_INFO"].unique()
reporters

array([nan, 'DBA: PHARMA PAC', 'PHARMACY MATERIAL SERVICES',
       'DBA/MWI ANIMAL HEALTH', 'ASSOCIATED PHARMACIES INC',
       'PHARMACEUTICAL DISTRIBUTOR', 'DANIEL HACKLEY, WAREHOUSE MANAGER',
       'D/B/A APIRX', 'DBA HENRY SCHEIN ANIMAL HEALTH',
       'DBA: RIVER CITY PHARMA', 'EXPERT-MED/LETCO MEDICAL',
       'DBA MAJOR PHARMACEUTICALS/RUGBY LABORATORIES',
       '172 RAILROAD AVENUE', 'PRESCRIPT', 'DISTRIBUTION, INC.',
       'DBA CURASCRIPT SD SPECIALTY', 'DBA  CURASCRIPT SD SPECIALTY',
       'D/B/A PARMED PHARMACEUTICALS', 'REDPHARM DRUG',
       'EXPERT MED/FIRST VETERINARY SUPPLY',
       'AMERICAN HEALTH SERVICE SALES CO DBA MED-VET INT.',
       'VICTOR INSTRUMENTS', 'SUPPLY CORP,', 'D/B/A R & S NORTHEAST LLC',
       'SEACOAST MEDICAL', 'DBA GIV', 'D/B/A PAR PHARMACEUTICAL',
       'A WALCO INTERNATIONAL INC CO', 'HILDA A. DOMINGUEZ',
       'FMC DISTRIBUTORS, INC.', 'DBA QUALITY CARE PRODUCTS LLC',
       'BURKE HORTON, INC D/B/A THE RX EXCHANGE'], dtype=object)

In [6]:
# View values in Column [5]
reporters_a2 = df["REPORTER_ADDRESS2"].unique()
reporters_a2

array([nan, 'REC DOOR D', '4836 SOUTHRIDGE BLVD', '3775 SEAPORT BLVD',
       '9700 SW COMMERCE CIRCLE', '1900 SOUTH 4490 WEST', 'PO BOX 5955',
       '2401 LUNT AVENUE', '1111 SOUTH ADAMS STREET', 'SUITE #400A',
       'UNIT B', 'SUITE 110', '740 GLASGOW AVE.',
       '7940 W DOE AVENUE SUITE 400', 'STOCKROOM 07',
       '31778 ENTERPRISE DRIVE', '8330 ARJONS DRIVE', 'BUILDING 200',
       'UNIT E', 'SUITE G', 'SUITE 101', '3000 KENSKILL AVE',
       'SUITE #100', 'UNIT 104', '#D', 'SUITE 1100', 'ONE SOUTHERN COURT',
       '2297  SOUTHWEST  BLVD   SUITE  #D',
       '995  S.  MC CARRAN  BLVD  SUITE #106', '5305 W BUCKEYE RD',
       '1755 EAST BEAMER STREET', 'SUITE 100', '2370 E MAIN STREET',
       'SUITE 102-A', '14500 E 39TH AVE', '13822 W BOULTON BLVD',
       'SUITE # 400', 'SUITE B', '5315 WEST 74TH STREET',
       '4220 HYDE PARK BLVD', '3820 TWIN CREEKS DRIVE', 'SUITE A',
       'P.O. BOX 9', '255 VISTA BLVD', 'PO BOX 270', 'SUITE D', 'BLDG# 4',
       '212 N. ANN ARBOR', 'PO BOX 270358', '3025 ROAD 591', 'SUITE 2',
       'SUITES 3,4,5 &6', '1001 AIRPARK DRIVE', 'STE #130'], dtype=object)

In [7]:
# View values in Column [22]
drug_code = df["DRUG_CODE"].unique()
drug_code

array([9143, 9193])

In [8]:
# View values in Column [26]
unit = df["UNIT"].unique()
unit
#>> units of PILLs

array([nan])

In [9]:
# View values in Column [25], for reference to Col 26
unit = df["QUANTITY"].unique()
unit
#>>determination: this the quantity of the transaction

array([3.000e+00, 1.000e+00, 6.000e+00, 2.000e+00, 4.000e+00, 1.200e+01,
       8.000e+00, 2.400e+01, 3.000e+01, 3.600e+01, 1.320e+02, 1.440e+02,
       2.160e+02, 6.000e+01, 2.880e+02, 1.200e+02, 1.920e+02, 7.200e+01,
       9.600e+01, 4.800e+01, 1.680e+02, 1.000e+01, 1.500e+01, 5.000e+00,
       2.800e+01, 2.000e+02, 3.000e+02, 2.520e+02, 2.640e+02, 2.400e+02,
       9.800e+01, 2.040e+02, 1.560e+02, 7.000e+00, 1.600e+01, 2.000e+01,
       1.100e+01, 5.000e+01, 1.900e+01, 1.800e+01, 9.000e+00, 1.700e+01,
       1.400e+01, 2.500e+01, 1.300e+01, 2.200e+01, 1.800e+02, 2.300e+01,
       2.100e+01, 2.600e+01, 3.200e+01, 4.000e+01, 8.000e+01, 5.700e+01,
       3.900e+01, 5.900e+01, 3.100e+01, 2.900e+01, 4.600e+01, 7.100e+01,
       7.300e+01, 8.900e+01, 6.600e+01, 1.240e+02, 1.120e+02, 4.100e+01,
       6.200e+01, 8.400e+01, 1.080e+02, 1.540e+02, 1.260e+02, 4.900e+01,
       1.230e+02, 3.500e+01, 3.700e+01, 1.500e+02, 7.800e+01, 1.040e+02,
       3.400e+01, 1.130e+02, 6.300e+01, 3.300e+01, 7.000e+01, 2.700e+01,
       1.000e+02, 8.000e+02, 9.600e+02, 2.500e+02, 3.840e+02, 6.720e+02,
       5.400e+01, 9.000e+01, 4.300e+01, 4.200e+01, 4.400e+01, 9.300e+01,
       1.170e+02, 5.300e+01, 9.200e+01, 3.800e+01, 5.200e+01, 4.500e+01,
       5.100e+01, 6.100e+01, 2.980e+02, 4.200e+02, 1.344e+03, 5.500e+01,
       1.180e+02, 2.380e+02, 6.700e+01, 1.210e+02, 2.610e+02, 1.090e+02,
       1.420e+02, 5.600e+01, 6.960e+02, 8.500e+01, 3.120e+02, 6.000e+02,
       1.200e+03, 4.560e+02, 1.320e+03, 5.280e+02, 6.900e+01, 1.850e+02,
       3.960e+02, 4.690e+02, 7.200e+02, 7.700e+01, 2.440e+02, 4.700e+01,
       7.500e+01, 3.600e+02, 1.080e+03, 3.360e+02, 5.000e+02, 2.280e+02,
       1.440e+03, 6.480e+02, 5.760e+02, 2.060e+02, 1.340e+02, 1.050e+02,
       5.200e+02, 1.032e+03, 8.400e+02, 2.460e+02, 4.000e+02, 4.080e+02,
       3.400e+02, 5.800e+01, 1.150e+02, 7.900e+01, 1.020e+02, 1.310e+02,
       9.700e+01, 1.152e+03, 4.320e+02, 1.520e+02, 1.060e+02, 1.330e+02,
       6.500e+01, 8.600e+01, 8.300e+01, 6.400e+01, 6.800e+01, 9.400e+01,
       4.800e+02, 5.400e+02, 6.240e+02, 4.240e+02, 8.200e+01, 1.960e+02,
       7.440e+02, 1.750e+02, 3.080e+02, 1.100e+02, 3.480e+02, 1.160e+02,
       5.520e+02, 6.144e+03, 3.920e+02, 7.920e+02, 2.000e+03, 9.900e+01,
       9.000e+02, 9.980e+02, 1.010e+02, 2.240e+02, 9.840e+02, 9.120e+02,
       8.640e+02, 1.584e+03, 1.400e+02, 1.660e+02, 8.440e+02, 5.180e+02,
       2.200e+02, 8.160e+02, 7.400e+01, 9.500e+01, 4.400e+02, 1.600e+02,
       8.100e+01, 1.980e+02, 1.740e+02, 2.340e+02, 6.300e+02, 4.820e+02,
       7.860e+02, 1.464e+03, 1.128e+03, 1.410e+02, 5.040e+02, 1.560e+03,
       2.448e+03, 8.700e+01, 4.520e+02, 1.030e+02, 1.730e+02, 1.820e+02,
       6.600e+02, 2.960e+02, 7.680e+02, 1.392e+03, 3.460e+02, 1.460e+02,
       1.280e+02, 2.300e+02, 1.270e+02, 3.200e+02, 1.480e+02, 2.560e+02,
       7.600e+01, 2.020e+02, 9.360e+02, 2.680e+02, 1.104e+03, 2.100e+02,
       5.700e+02, 1.110e+02, 1.220e+02, 5.080e+02, 1.070e+02, 2.800e+02,
       1.720e+02, 1.370e+02])

In [10]:
# Which rows are missing data?

df.count()

REPORTER_DEA_NO          3492615
REPORTER_BUS_ACT         3492615
REPORTER_NAME            3492615
REPORTER_ADDL_CO_INFO      27733
REPORTER_ADDRESS1        3492615
REPORTER_ADDRESS2        2087681
REPORTER_CITY            3492615
REPORTER_STATE           3492615
REPORTER_ZIP             3492615
REPORTER_COUNTY          3492615
BUYER_DEA_NO             3492615
BUYER_BUS_ACT            3492615
BUYER_NAME               3492615
BUYER_ADDL_CO_INFO       1777698
BUYER_ADDRESS1           3492615
BUYER_ADDRESS2            927778
BUYER_CITY               3492615
BUYER_STATE              3492615
BUYER_ZIP                3492615
BUYER_COUNTY             3492615
TRANSACTION_CODE         3492615
DRUG_CODE                3492615
NDC_NO                   3492615
DRUG_NAME                3492615
QUANTITY                 3492615
UNIT                           0
ACTION_INDICATOR            7196
ORDER_FORM_NO            1615188
CORRECTION_NO                894
STRENGTH                  589425
TRANSACTION_DATE         3492615
CALC_BASE_WT_IN_GM       3492615
DOSAGE_UNIT              3492615
TRANSACTION_ID           3492615
Product_Name             3492615
Ingredient_Name          3492615
Measure                  3492615
MME_Conversion_Factor    3492615
Combined_Labeler_Name    3491981
Reporter_family          3492615
dos_str                  3485212
MME                      3492615
dtype: int64

In [11]:
#What are we working with?

df.dtypes

REPORTER_DEA_NO           object
REPORTER_BUS_ACT          object
REPORTER_NAME             object
REPORTER_ADDL_CO_INFO     object
REPORTER_ADDRESS1         object
REPORTER_ADDRESS2         object
REPORTER_CITY             object
REPORTER_STATE            object
REPORTER_ZIP               int64
REPORTER_COUNTY           object
BUYER_DEA_NO              object
BUYER_BUS_ACT             object
BUYER_NAME                object
BUYER_ADDL_CO_INFO        object
BUYER_ADDRESS1            object
BUYER_ADDRESS2            object
BUYER_CITY                object
BUYER_STATE               object
BUYER_ZIP                  int64
BUYER_COUNTY              object
TRANSACTION_CODE          object
DRUG_CODE                  int64
NDC_NO                    object
DRUG_NAME                 object
QUANTITY                 float64
UNIT                     float64
ACTION_INDICATOR          object
ORDER_FORM_NO             object
CORRECTION_NO            float64
STRENGTH                 float64
TRANSACTION_DATE           int64
CALC_BASE_WT_IN_GM       float64
DOSAGE_UNIT              float64
TRANSACTION_ID             int64
Product_Name              object
Ingredient_Name           object
Measure                   object
MME_Conversion_Factor    float64
Combined_Labeler_Name     object
Reporter_family           object
dos_str                  float64
MME                      float64
dtype: object

In [18]:
df['BUYER_DEA_NO'].nunique()

1920

In [13]:
df['BUYER_COUNTY'].value_counts()
# >>>NOTE>>> We'll want to find county populations to find per capita distribution

MULTNOMAH     532390
LANE          372426
CLACKAMAS     354064
WASHINGTON    346636
JACKSON       253103
MARION        233278
DESCHUTES     152459
LINN          143253
DOUGLAS       132729
JOSEPHINE     106526
COOS           87684
YAMHILL        85793
UMATILLA       74239
LINCOLN        67892
KLAMATH        60531
BENTON         59393
COLUMBIA       49800
CLATSOP        49007
POLK           46251
MALHEUR        36604
WASCO          34559
UNION          34246
CURRY          32160
TILLAMOOK      32005
BAKER          22513
HOOD RIVER     19263
CROOK          18076
JEFFERSON      14484
HARNEY          9287
LAKE            8606
WALLOWA         8497
GRANT           7507
MORROW          5368
GILLIAM         1949
WHEELER           37
Name: BUYER_COUNTY, dtype: int64

In [14]:
df['REPORTER_DEA_NO'].value_counts()

PM0022929    1319014
RW0191813     613343
RA0290938     331700
RW0204026     299373
RW0186278     209821
              ...
RM0178675          1
PP0040167          1
RT0278704          1
RN0371269          1
RN0281054          1
Name: REPORTER_DEA_NO, Length: 180, dtype: int64

In [15]:
#BIGGEST PICTURE: COUNTIES, QUANTITIES
sky_high_df = df[["BUYER_COUNTY", "BUYER_DEA_NO", "DRUG_NAME", "QUANTITY"]]
sky_high_df.head()

  BUYER_COUNTY BUYER_DEA_NO    DRUG_NAME  QUANTITY
0    DESCHUTES    BB8388010    OXYCODONE       3.0
1         LANE    BB9517559  HYDROCODONE       1.0
2    CLACKAMAS    BC8673279  HYDROCODONE       6.0
3    MULTNOMAH    BG8412847  HYDROCODONE       2.0
4    MULTNOMAH    BG8412847  HYDROCODONE       1.0

In [16]:
# Create a dataframe of the average stats for each county
county_group = df.groupby(["BUYER_COUNTY"])

county_comparison_df = county_group.mean()

#pokemon_comparison_df = pokemon_group.mean()
county_comparison_df

#>>> THIS DISPLAYED EVVVVERYYY THING

,REPORTER_ZIP,BUYER_ZIP,DRUG_CODE,QUANTITY,UNIT,CORRECTION_NO,STRENGTH,TRANSACTION_DATE,CALC_BASE_WT_IN_GM,DOSAGE_UNIT,TRANSACTION_ID,MME_Conversion_Factor,dos_str,MME
BUYER_COUNTY,,,,,,,,,,,,,,
BAKER,88830.768400,97814.000000,9172.469640,2.517834,NaN,5.559500e+03,260.141661,6.723401e+06,2.665287,421.962866,7.586784e+08,1.205304,10.990364,3326.131376
BENTON,93431.800431,97331.405351,9169.445877,2.802435,NaN,1.854285e+07,152.658903,6.695521e+06,2.488299,387.109592,8.827235e+08,1.235541,10.708052,3316.632172
CLACKAMAS,92096.691937,97078.315646,9168.355444,3.769999,NaN,1.208396e+07,167.744171,6.736941e+06,3.493800,524.681696,6.266912e+08,1.246446,11.554887,4698.170452
CLATSOP,93269.243067,97131.417430,9169.859428,3.252127,NaN,3.969169e+06,0.000000,6.691273e+06,3.720626,486.927378,6.588912e+08,1.231406,12.735899,5015.115849
COLUMBIA,92485.591386,97049.259036,9169.954819,2.638855,NaN,1.567000e+03,0.000000,6.712515e+06,2.551819,396.019679,7.702008e+08,1.230452,11.577691,3384.733688
COOS,91992.294033,97431.150084,9176.198189,2.926372,NaN,2.329083e+07,0.000000,6.638638e+06,2.944967,464.466607,7.842268e+08,1.168018,10.818441,3650.232182
CROOK,94499.981688,97754.000000,9172.680239,2.768644,NaN,1.187634e+07,0.000000,6.786981e+06,2.794717,499.572914,9.262134e+08,1.203198,9.641220,3448.818286
CURRY,92669.511847,97421.960386,9174.127177,2.597450,NaN,5.416857e+03,0.000000,6.646494e+06,3.829000,523.860354,7.815748e+08,1.188728,12.789816,4778.417274
DESCHUTES,92620.960560,97723.640821,9171.540460,2.568756,NaN,7.135715e+06,105.755576,6.721942e+06,2.315139,413.053470,8.195091e+08,1.214595,9.399503,2961.853159
DOUGLAS,92802.371449,97468.247550,9171.105764,2.898334,NaN,4.878113e+06,174.022773,6.716813e+06,3.326192,453.711322,7.852041e+08,1.218942,11.397800,4385.378230
GILLIAM,97152.121088,97823.000000,9176.555670,1.320164,NaN,NaN,0.000000,6.683683e+06,1.585297,284.515136,1.085508e+09,1.164443,9.727786,1863.883599
GRANT,95585.307313,97847.851738,9166.058479,2.125883,NaN,1.569500e+03,0.335852,6.771198e+06,2.320571,381.763687,1.069953e+09,1.269415,10.175197,3010.580282
HARNEY,96981.689135,97725.112954,9171.652956,2.320879,NaN,1.151186e+07,0.000000,6.681302e+06,1.968723,324.877786,8.920797e+08,1.213470,9.457345,2538.476809
HOOD RIVER,93811.135649,97031.000000,9175.988112,2.522920,NaN,5.194250e+03,0.000000,6.703260e+06,2.414165,430.988423,6.570557e+08,1.170119,9.547745,3040.550448
JACKSON,91522.105613,97510.796656,9170.090157,3.365511,NaN,1.231235e+07,332.981242,6.695213e+06,3.785682,493.100888,6.658386e+08,1.229098,12.353433,5004.582461
JEFFERSON,95719.534314,97741.013946,9172.788042,2.286316,NaN,NaN,0.000000,6.722407e+06,2.392644,457.547639,9.948025e+08,1.202120,8.777463,2931.695654
JOSEPHINE,92126.658468,97525.884789,9171.482248,3.242147,NaN,7.272629e+06,227.880795,6.708408e+06,3.765543,561.829901,7.746201e+08,1.215178,11.566831,4802.390856
KLAMATH,90568.399828,97602.491517,9175.544481,3.149163,NaN,1.523376e+07,333.084280,6.648923e+06,3.104385,520.862368,7.515090e+08,1.174555,10.299113,3816.546808
LAKE,93973.519405,97630.021729,9168.807576,2.211945,NaN,2.379992e+07,0.000000,6.798392e+06,3.171900,575.225424,9.963583e+08,1.241924,10.815123,3985.230616
LANE,90397.331537,97432.880508,9169.843319,3.037543,NaN,1.646039e+07,323.692029,6.716168e+06,3.147090,459.865299,7.137688e+08,1.231567,11.364821,4178.293075
LINCOLN,92180.692806,97369.798062,9170.936281,3.502651,NaN,2.013288e+07,0.000000,6.703497e+06,3.399158,486.152713,7.537331e+08,1.220637,11.512724,4488.169954
LINN,94284.628901,97342.906829,9170.032593,2.779258,NaN,2.028514e+07,63.135216,6.722411e+06,2.716722,419.748382,8.502095e+08,1.229674,11.198891,3601.577869
MALHEUR,86577.771582,97914.293137,9177.459349,2.697328,NaN,2.496600e+07,0.000000,6.726054e+06,2.928093,459.900284,5.852750e+08,1.155407,10.662723,3484.378941
MARION,93426.911586,97292.832286,9170.140150,3.423439,NaN,2.250812e+07,0.000000,6.712880e+06,3.248666,514.288205,6.830322e+08,1.228598,11.017711,4353.727887
MORROW,96661.522541,97827.694113,9175.852086,1.620715,NaN,NaN,0.000000,6.701585e+06,1.593061,309.381520,1.023546e+09,1.171479,8.193590,1907.900530
MULTNOMAH,92474.150360,97186.346353,9169.392588,5.077120,NaN,6.955361e+06,53.298267,6.695990e+06,4.190410,648.387421,5.555700e+08,1.236074,11.535210,5639.526661
POLK,93512.783378,97333.862511,9171.391819,2.769583,NaN,8.480546e+06,0.330242,6.711388e+06,2.689908,462.443190,8.350110e+08,1.216082,10.267130,3522.253904
TILLAMOOK,89312.766786,97138.255054,9170.095766,2.886830,NaN,2.496619e+07,0.000000,6.654919e+06,4.390402,529.637244,6.314116e+08,1.229042,13.291491,5814.911836
UMATILLA,91620.483075,97831.431135,9175.521316,2.631743,NaN,1.334203e+07,0.208261,6.693215e+06,2.371968,413.871799,8.982217e+08,1.174787,9.442514,2983.599298
UNION,85224.239327,97851.823717,9169.011797,2.532646,NaN,3.288000e+03,0.000000,6.730199e+06,2.753662,408.368277,8.320230e+08,1.239882,11.823949,3635.207858
WALLOWA,90733.556079,97830.550900,9174.069789,1.836177,NaN,NaN,0.000000,6.672207e+06,2.074570,330.974462,9.128821e+08,1.189302,11.159467,2607.101193
WASCO,91488.766255,97057.976301,9173.921034,2.954513,NaN,1.547334e+07,0.096810,6.721602e+06,2.849716,479.336497,6.169863e+08,1.190790,9.867030,3604.542267
WASHINGTON,92789.532778,97116.594422,9167.826908,3.659790,NaN,2.019814e+07,87.841722,6.698957e+06,3.233965,491.255839,5.601499e+08,1.251731,11.375811,4373.979471
WHEELER,60048.000000,97830.000000,9193.000000,1.513514,NaN,NaN,NaN,5.298497e+06,0.027488,9.081081,1.116054e+03,1.000000,5.000000,27.488432
YAMHILL,92611.321087,97153.807327,9168.454874,2.530568,NaN,3.296884e+06,143.063402,6.710407e+06,2.500001,409.133391,6.114844e+08,1.245451,10.928240,3288.324973

In [17]:
# Big one, take two:
# Create a dataframe of the average stats for each county
county_group = sky_high_df.groupby(["BUYER_COUNTY"])

county_comparison_df = county_group.sum()

# #county_comparison_df = county_group.mean()
county_comparison_df

##>>NOTE - will need to separate hydro from oxy for a clearer picture (USE LOC)

               QUANTITY
BUYER_COUNTY
BAKER           56684.0
BENTON         166445.0
CLACKAMAS     1334821.0
CLATSOP        159377.0
COLUMBIA       131415.0
COOS           256596.0
CROOK           50046.0
CURRY           83534.0
DESCHUTES      391630.0
DOUGLAS        384693.0
GILLIAM          2573.0
GRANT           15959.0
HARNEY          21554.0
HOOD RIVER      48599.0
JACKSON        851821.0
JEFFERSON       33115.0
JOSEPHINE      345373.0
KLAMATH        190622.0
LAKE            19036.0
LANE          1131260.0
LINCOLN        237802.0
LINN           398137.0
MALHEUR         98733.0
MARION         798613.0
MORROW           8700.0
MULTNOMAH     2703008.0
POLK           128096.0
TILLAMOOK       92393.0
UMATILLA       195378.0
UNION           86733.0
WALLOWA         15602.0
WASCO          102105.0
WASHINGTON    1268615.0
WHEELER            56.0
YAMHILL        217105.0

In [ ]:
# # From Pandas 2 activity 7

# # Create a dataframe of the average stats for each type of pokemon.
# pokemon_group = pokemon_type_df.groupby(["Type 1"])


# pokemon_comparison_df = pokemon_group.mean()

# #pokemon_comparison_df = pokemon_group.mean()
# pokemon_comparison_df

In [ ]:
# # from 04 Pandas Day 2 act. 4

# # Create a new DataFrame that looks into a specific neighborhood
# vernon_crime_df = no_null_crime_df.loc[no_null_crime_df["Neighborhood"] == "Vernon"]
# vernon_crime_df

In [23]:
# REPORTER_DEA_NO
# REPORTER_BUS_ACT (activity, what they do with drug)
# reporter_name
# BUYER_DEA_NO
# BUYER_BUS_ACT (activity, what they do with drug)
# BUYER_NAME
# BUYER_COUNTY
# DRUG_NAME
# Transaction_ID
# Product_Name (has dosage numbers)
# MME

#BIGGEST PICTURE: COUNTIES, QUANTITIES
oregon_data_df = df[["REPORTER_DEA_NO","REPORTER_BUS_ACT", "REPORTER_NAME", "BUYER_DEA_NO", "BUYER_BUS_ACT", "BUYER_NAME","BUYER_COUNTY", "DRUG_NAME", "TRANSACTION_ID", "Product_Name" , "MME"]]
oregon_data_df.head()

,REPORTER_DEA_NO,REPORTER_BUS_ACT,REPORTER_NAME,BUYER_DEA_NO,BUYER_BUS_ACT,BUYER_NAME,BUYER_COUNTY,DRUG_NAME,TRANSACTION_ID,Product_Name,MME
0,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BB8388010,CHAIN PHARMACY,BI-MART LA PINE 671,DESCHUTES,OXYCODONE,5029,OXYCODONE HCL 40MG TABS,16137.00
1,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BB9517559,RETAIL PHARMACY,BHS EUGENE INC.,LANE,HYDROCODONE,1592,HYDROCODONE.BIT. & ACETA 5MG & 500M,3027.00
2,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BC8673279,RETAIL PHARMACY,CONSONUS PHARMACY SERVICES,CLACKAMAS,HYDROCODONE,331,HYDROCODONE BITARTRATE/ACETA 7.5MG/3,2724.30
3,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,HYDROCODONE,8633,"HYDROCODONE.BIT./ACET.,10MG & 325MG/",6054.00
4,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,HYDROCODONE,7829,HYDROCODONE/APAP 7.5MG/200MG TABS.,2270.25

In [25]:
#CHECK COLUMN LENGTH 
oregon_data_df.count()

REPORTER_DEA_NO     3492615
REPORTER_BUS_ACT    3492615
REPORTER_NAME       3492615
BUYER_DEA_NO        3492615
BUYER_BUS_ACT       3492615
BUYER_NAME          3492615
BUYER_COUNTY        3492615
DRUG_NAME           3492615
TRANSACTION_ID      3492615
Product_Name        3492615
MME                 3492615
dtype: int64

In [38]:
# OR = MULTNOMAH ONLY

OR_county_df = oregon_data_df.loc[oregon_data_df["BUYER_COUNTY"]=="MULTNOMAH"]
OR_county_df

,REPORTER_DEA_NO,REPORTER_BUS_ACT,REPORTER_NAME,BUYER_DEA_NO,BUYER_BUS_ACT,BUYER_NAME,BUYER_COUNTY,DRUG_NAME,TRANSACTION_ID,Product_Name,MME
3,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,HYDROCODONE,8633,"HYDROCODONE.BIT./ACET.,10MG & 325MG/",6054.0000
4,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,HYDROCODONE,7829,HYDROCODONE/APAP 7.5MG/200MG TABS.,2270.2500
20,PH0234928,MANUFACTURER,H J HARKINS COMPANY INC,BH6960024,PRACTITIONER,"HALL, DAVID Z MD",MULTNOMAH,HYDROCODONE,813,HYDROCODONE BIT/ACETAMINOPHEN 5MG/50,605.4000
30,PK0132821,DISTRIBUTOR,KAISER FNDTN HEALTH PLAN NW,AK7799008,RETAIL PHARMACY,KAISER PERMANENTE,MULTNOMAH,OXYCODONE,387,OXYCODONE HYDROCHLORIDE EXTENDED-REL,80685.0000
31,PK0132821,DISTRIBUTOR,KAISER FNDTN HEALTH PLAN NW,AK7799008,RETAIL PHARMACY,KAISER PERMANENTE,MULTNOMAH,OXYCODONE,216,OXYCODONE HYDROCHLORIDE EXTENDED-REL,80685.0000
...,...,...,...,...,...,...,...,...,...,...,...
3492581,RD0274364,MANUFACTURER,DISPENSING SOLUTIONS,BH0533085,PRACTITIONER,"HOSKO, MARK E MD",MULTNOMAH,HYDROCODONE,1301,HYDROCODONE/APAP 5MG/500MG TABLETS,665.9400
3492592,RD0277409,DISTRIBUTOR,"MASTERS PHARMACEUTICAL, INC",BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,OXYCODONE,2885,OXYCODONE HCL/ACETAMINOPHEN 7.5MG/32,2017.1250
3492593,RD0277409,DISTRIBUTOR,"MASTERS PHARMACEUTICAL, INC",BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,OXYCODONE,1735,OXYCODONE HCL/ACETAMINOPHEN 10MG/325,5379.0000
3492594,RD0277409,DISTRIBUTOR,"MASTERS PHARMACEUTICAL, INC",BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,OXYCODONE,5014,OXYCODONE HCL/ACETAMINOPHEN TABS 5MG,6723.7500
3492595,RD0277409,DISTRIBUTOR,"MASTERS PHARMACEUTICAL, INC",BG8412847,RETAIL PHARMACY,GRESHAM PROFESSIONAL PHARMACY,MULTNOMAH,OXYCODONE,456,ENDOCET - 7.5MG OXYCODONE.HCL/325MG,1008.5625

In [26]:
#BIGGEST PICTURE: COUNTIES, QUANTITIES
washington_data_df = wa_df[["REPORTER_DEA_NO","REPORTER_BUS_ACT", "REPORTER_NAME", "BUYER_DEA_NO", "BUYER_BUS_ACT", "BUYER_NAME","BUYER_COUNTY", "DRUG_NAME", "TRANSACTION_ID", "Product_Name" , "MME"]]
washington_data_df.head()

,REPORTER_DEA_NO,REPORTER_BUS_ACT,REPORTER_NAME,BUYER_DEA_NO,BUYER_BUS_ACT,BUYER_NAME,BUYER_COUNTY,DRUG_NAME,TRANSACTION_ID,Product_Name,MME
0,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,AC8948056,RETAIL PHARMACY,"CHINOOK PHARMACY, INC",CLALLAM,HYDROCODONE,4210,HYDROCODONE BIT. & IBUPROPHEN 7.5MG/,3632.4
1,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,AC8948056,RETAIL PHARMACY,"CHINOOK PHARMACY, INC",CLALLAM,HYDROCODONE,4123,HYDROCODONE BIT/ACETA 5MG/325MG USP,302.7
2,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,AN8909888,RETAIL PHARMACY,NICHOLSON'S SUMNER PHARMACY,PIERCE,OXYCODONE,4031,OXYCODONE HYDROCHLORIDE CR 20MG TABL,8068.5
3,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BB7776149,RETAIL PHARMACY,BATES PHARMACY AND MEDICAL,SPOKANE,HYDROCODONE,7551,HYDROCODONE BIT. 10MG/ACETAMINOPHEN,3027.0
4,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,BB7776149,RETAIL PHARMACY,BATES PHARMACY AND MEDICAL,SPOKANE,HYDROCODONE,4807,HYDROCODONE BIT. 10MG/ACETAMINOPHEN,3027.0

In [27]:
washington_data_df.count()

REPORTER_DEA_NO     5423267
REPORTER_BUS_ACT    5423267
REPORTER_NAME       5423267
BUYER_DEA_NO        5423267
BUYER_BUS_ACT       5423267
BUYER_NAME          5423267
BUYER_COUNTY        5423267
DRUG_NAME           5423267
TRANSACTION_ID      5423267
Product_Name        5423267
MME                 5423267
dtype: int64

In [44]:
# WA = CLARK ONLY

WA_county_df = washington_data_df.loc[washington_data_df["BUYER_COUNTY"]=="CLARK"]
WA_county_df

,REPORTER_DEA_NO,REPORTER_BUS_ACT,REPORTER_NAME,BUYER_DEA_NO,BUYER_BUS_ACT,BUYER_NAME,BUYER_COUNTY,DRUG_NAME,TRANSACTION_ID,Product_Name,MME
22,PK0132821,DISTRIBUTOR,KAISER FNDTN HEALTH PLAN NW,AK7768952,RETAIL PHARMACY,KAISER FOUNDATION HEALTH PLAN,CLARK,OXYCODONE,288,ENDOCET OXYCODO HCL5MG&AC TAB,48405.600
23,PK0132821,DISTRIBUTOR,KAISER FNDTN HEALTH PLAN NW,AK7768952,RETAIL PHARMACY,KAISER FOUNDATION HEALTH PLAN,CLARK,HYDROCODONE,380,HYDROCODONE BIT. & APAP 5MG/500MG TA,2905.920
24,PK0132821,DISTRIBUTOR,KAISER FNDTN HEALTH PLAN NW,AK7768952,RETAIL PHARMACY,KAISER FOUNDATION HEALTH PLAN,CLARK,HYDROCODONE,359,HYDROCODONE BIT./ACETAMINOPHEN 5MG/3,1816.200
46,PK0132821,DISTRIBUTOR,KAISER FNDTN HEALTH PLAN NW,BK1783263,RETAIL PHARMACY,KAISER PERMANENTE CASCADE,CLARK,OXYCODONE,84,ENDOCET OXYCODO HCL5MG&AC TAB,32270.400
47,PK0132821,DISTRIBUTOR,KAISER FNDTN HEALTH PLAN NW,BK1783263,RETAIL PHARMACY,KAISER PERMANENTE CASCADE,CLARK,OXYCODONE,107,ENDOCET OXYCODO HCL5MG&AC TAB,32270.400
...,...,...,...,...,...,...,...,...,...,...,...
5423169,RD0269109,MANUFACTURER,"DRX PHARMACEUTICAL CONSULTANTS, INC.",BB9063001,PRACTITIONER,"BODROUG, BOGDAN NIKOLAYEVICH",CLARK,HYDROCODONE,1536,HYDROCOD. BIT 5MG TAB,726.480
5423170,RD0269109,MANUFACTURER,"DRX PHARMACEUTICAL CONSULTANTS, INC.",BB9063001,PRACTITIONER,"BODROUG, BOGDAN NIKOLAYEVICH",CLARK,HYDROCODONE,752,HYDROCOD. BIT 5MG TAB,726.480
5423179,RD0269109,MANUFACTURER,"DRX PHARMACEUTICAL CONSULTANTS, INC.",BH2662004,PRACTITIONER,"HAMMON, ROBERT L DDS",CLARK,HYDROCODONE,1477,HYDROCOD. BIT 5MG TAB,217.944
5423198,RD0271130,DISTRIBUTOR,"DARBY DENTAL SUPPLY, LLC",BB9063001,PRACTITIONER,"BODROUG, BOGDAN NIKOLAYEVICH",CLARK,HYDROCODONE,518,HYDROCODO.BIT5MG/AC TAB,726.480
5423228,RD0277409,DISTRIBUTOR,"MASTERS PHARMACEUTICAL, INC",AB7851404,RETAIL PHARMACY,"BATTLE GROUND PHARMACY, INC",CLARK,OXYCODONE,5502,OXYCODONE HCL 20MG IR BLEND TABS,2689.500

In [45]:
WA_county_df.to_csv(r'CSV_files/WA_county_data.csv', index=False)

In [42]:
OR_county_df.to_csv(r'CSV_files/OR_county_data.csv', index=False)

In [ ]:
# documentation of process
# reducing files to be available on github for ETL demonstration